# Generated by Django 3.0.6 on 2020-08-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200819_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alert',
            field=models.CharField(default='', max_length=100),
        ),
    ]
