# Generated by Django 3.0.6 on 2020-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alert',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
