# Generated by Django 3.0.7 on 2020-08-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200821_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alert',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
