# Generated by Django 3.0.7 on 2020-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('multiplication_factor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_bid_price', models.IntegerField()),
                ('percentage_for_sale', models.IntegerField()),
            ],
        ),
    ]
