# Generated by Django 3.0.7 on 2020-08-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_trading_highets_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='your_bid_price',
            field=models.IntegerField(default=0),
        ),
    ]
