# Generated by Django 3.0.7 on 2020-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200812_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradinglive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_bid_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='trading',
            name='your_bid_price',
        ),
    ]
