# Generated by Django 3.0.7 on 2020-08-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bidding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trading',
            name='percentage_for_sale',
        ),
    ]
