# Generated by Django 3.0.7 on 2020-08-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_trading_percentage_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_details_trading', to='home.Company'),
        ),
    ]
