# Generated by Django 3.0.6 on 2020-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tradinglive_trading_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='your_bid_price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Tradinglive',
        ),
    ]
