# Generated by Django 3.0.7 on 2020-08-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200812_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trading',
            old_name='highets_bid',
            new_name='highest_bid',
        ),
    ]
