# Generated by Django 3.0.7 on 2020-08-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200813_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='percentage_for_sale',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
