# Generated by Django 3.0.7 on 2020-08-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_trading_percentage_for_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trading',
            name='company',
        ),
        migrations.AddField(
            model_name='trading',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_details_trading', to='home.Company'),
        ),
    ]
