# Generated by Django 3.0.7 on 2020-08-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200817_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trading',
            name='company',
        ),
        migrations.AddField(
            model_name='trading',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_details_trading', to='home.Company'),
        ),
    ]
