# Generated by Django 3.0.7 on 2020-08-18 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_auto_20200817_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='company',
        ),
        migrations.AddField(
            model_name='share',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='home.Company'),
        ),
        migrations.RemoveField(
            model_name='share',
            name='shareholder',
        ),
        migrations.AddField(
            model_name='share',
            name='shareholder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shareholder_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
