# Generated by Django 3.0.7 on 2020-08-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200818_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='multiplication_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='trading',
            name='percentage_for_sale',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
        ),
    ]
