# Generated by Django 3.0.7 on 2020-08-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200819_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
