# Generated by Django 3.0.7 on 2020-08-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200819_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bidding_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='share',
            name='percentage_of_share',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trading',
            name='highest_bid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trading',
            name='your_bid_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
