# Generated by Django 3.0.7 on 2020-08-19 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200820_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='percentage_of_share',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
